parameters:
  - name: DownloadCUDA
    type: boolean
    default: false
  - name: DownloadTRT
    type: boolean
    default: false
  - name: CUDA_Version
    type: string
    default: '11.8'
    values:
      - '11.8'
      - '12.2'
variables:
  - template: variables/win_gpu_library_variables.yml
steps:
  - ${{ if eq(parameters.DownloadCUDA, true) }}:
      - powershell: |
          azcopy.exe cp --recursive ${{ variables.cuda_sdk_url }} $(Agent.TempDirectory)
        displayName: 'Download CUDA SDK v${{ parameters.CUDA_Version }}'
      - powershell: |
          Write-Host "##vso[task.prependpath]$(Agent.TempDirectory)\v${{ parameters.CUDA_Version }}\bin;$(Agent.TempDirectory)\v${{ parameters.CUDA_Version }}\extras\CUPTI\lib64"
        displayName: 'Append CUDA SDK Directory to PATH'
      - CmdLine@2:
          script: |
            echo %PATH%
        displayName: 'Print PATH'

  - ${{ if eq(parameters.DownloadTRT, true) }}:
      - powershell: |
          azcopy.exe cp --recursive ${{ variables.tensorrt_url }}, $(Agent.TempDirectory)
        displayName: 'Download ${{ variables.tensorrt_dir }}'
      - powershell: |
          Write-Host "##vso[task.prependpath]$(Agent.TempDirectory)\${{ variables.tensorrt_dir }}\lib"
        displayName: 'Append CUDA SDK Directory to PATH'
      - CmdLine@2:
          script: |
            echo %PATH%
        displayName: 'Print PATH'