parameters:
  - name: EnvSetupScript
    type: string
  - name: DownloadCUDA
    type: boolean
    default: false
  - name: DownloadTRT
    type: boolean
    default: false
  - name: PrimaryCUDAVersion
    type: string
    default: '11.8'
  - name: SecondaryCUDAVersion
    type: string
    default: '12.2'
  - name: PrimaryTensorRTVersion
    type: string
    default: 8.6.1.6.Windows10.x86_64.cuda-11.8
  - name: SecondaryTensorRTVersion
    type: string
    default: 8.6.1.6.Windows10.x86_64.cuda-12.0

steps:
  - ${{ if or(eq(parameters.DownloadCUDA, true), eq(parameters.DownloadTRT, true)) }}:
      - powershell: |
          azcopy.exe cp --recursive "https://lotusscus.blob.core.windows.net/models/cuda_sdk/v${{ parameters.PrimaryCUDAVersion }}" $(Agent.TempDirectory)
        displayName: 'Download Primary CUDA SDK v${{ parameters.PrimaryCUDAVersion }}'
      - powershell: |
          azcopy.exe cp --recursive "https://lotusscus.blob.core.windows.net/models/cuda_sdk/v${{ parameters.SecondaryCUDAVersion }}" $(Agent.TempDirectory)
        displayName: 'Download Secondary CUDA SDK v${{ parameters.SecondaryCUDAVersion }}'
  - $${{ if eq(parameters.DownloadTRT, true) }}:
      - powershell: |
          azcopy.exe cp --recursive "https://lotusscus.blob.core.windows.net/models/local/TensorRT-${{ parameters.PrimaryTensorRTVersion }}", $(Agent.TempDirectory)
        displayName: 'Download Primary TensorRT with version ${{ parameters.PrimaryTensorRTVersion }}'
      - powershell: |
          azcopy.exe cp --recursive "https://lotusscus.blob.core.windows.net/models/local/TensorRT-${{ parameters.SecondaryTensorRTVersion }}", $(Agent.TempDirectory)
        displayName: 'Download Secondary TensorRT with version ${{ parameters.SecondaryTensorRTVersion }}'
  - $${{ if eq(parameters.DownloadTRT, true) }}:
    - task: BatchScript@1
      displayName: 'setup env'
      inputs:
        filename: '$(Build.SourcesDirectory)\tools\ci_build\github\windows\${{ parameters.EnvSetupScript }}'
        modifyEnvironment: true
        workingFolder: '$(Build.BinariesDirectory)'
  - $${{ if and(eq(parameters.DownloadCUDA, true), ne(parameters.DownloadTRT, true)) }}:
    - task: BatchScript@1
      displayName: 'setup env'
      inputs:
        filename: '$(Build.SourcesDirectory)\tools\ci_build\github\windows\${{ parameters.EnvSetupScript }}'
        modifyEnvironment: true
        workingFolder: '$(Build.BinariesDirectory)'
